### ISSUE TITLE
Can we write how to execute this app on android and iOS in the README?

### ISSUE THREAD

**Issue by amunna** [filippofilip95/gas-oil-mixture-mobile#8]
Since this repository is linked at Facebook's react-native tutorial many of the visitors will be react-native beginners. It would be helpful to write the execution steps to run the app on android and iOS.

**Comment by filippofilip95** [comment]
I'll wrote it soon my friend :) today or tomorrow :)

**Comment by filippofilip95** [comment]
Added e5b555dc2575f5a307f45304ab8fd4102ef202c8
